fix gitclean

diff --git a/docker-build b/docker-build
--- a/docker-build
+++ b/docker-build
@@ -24,12 +24,12 @@ EOM
 
     while true ; do
         case "$1" in
-            -h | --help) usage; exit;;
-            --clone) git clone https://github.com/fdie/otp.git -b 19.2.3.1-cloud && cp $SCRIPT_NAME otp && cd otp; shift 2;;
-            --gitclean) GIT_CLEAN=1 ; echo "YES"; shift;;
-            -p | --delivery-dir) DELIVERY_VOLUME=$2; shift 2;;
-            --) shift ; break;;
-            *) echo "$1 => Internal error!"; exit 1;;
+            -h | --help) usage; exit ;;
+            --clone) git clone https://github.com/fdie/otp.git -b 19.2.3.1-cloud && cp $SCRIPT_NAME otp && cd otp; shift 2 ;;
+            --gitclean) GIT_CLEAN=1 ; echo "YES"; shift 2 ;;
+            -p | --delivery-dir) DELIVERY_VOLUME=$2; shift 2 ;;
+            --) shift ; break ;;
+            *) echo "$1 => Internal error!"; exit 1 ;;
         esac
     done
     if [[ $GIT_CLEAN = 1 ]]
